### ISSUE TITLE
Is there a way to disable this such that it defaults to the firmware config?

### ISSUE THREAD

**Issue by point-source** [fieldOfView/Cura-LinearAdvanceSettingPlugin#35] opened 2021-11-15 00:25 UTC
I noticed that simply having this plugin installed causes `M900 K0.000000 T0 ;added by LinearAdvanceSettingPlugin` to be written out to the gcode regardless of whether or not I have explicitly set a value.

My printer config file (klipper based) has a pressure_advance value set as default and I would like this to be used unless I choose to override it with this plugin. How can I achieve this?

**Comment by fieldOfView** [comment] 2022-04-15 15:35
Duplicate of #32

**Closed as completed by fieldOfView** 2022-04-15 15:35 UTC
