### ISSUE TITLE
Issue with Comma

### ISSUE THREAD

**Issue by DavidEnduro** [fieldOfView/Cura-LinearAdvanceSettingPlugin#2] opened 2018-10-29 15:42 UTC
Hey ;)

There are no comma numbers taken over. 
for example 0.4 
I need that for Linear Advance> v1.5

Thanks in advance.

Greets David

**Comment by fieldOfView** [comment] 2018-10-29 15:49
Ho (-;

Duplicate of #1 
I will post an updated version to the Toolbox

**Comment by DavidEnduro** [comment] 2018-10-29 15:57
Thanks ;)! 

Great Work!

**Comment by fieldOfView** [comment] 2018-11-21 14:35
The fixed version is not available in the ~Toolbox~Marketplace

**Closed as completed** 2019-01-24 08:24 UTC
